### ISSUE TITLE
Flipping cards

### ISSUE THREAD

**Issue by jenkin** [mattyX20/Superheroes#1]
> Salve prof le scrivo per un problema stavo cercando di inserire il flip alle cards dei personaggi, vado ad inserire crasha oopure fa il flip ma sparisce tutto
> Link a Github for code: https://github.com/mattyX20/Superheroes/tree/Develop 
> 
> Link library flip:
> http://nnattawat.github.io/flip/

(@mattyX20 on yammer at 9/1/2018)

**Comment by jenkin** [comment]
Nel codice attuale che vedo nella branch Develop non c'è traccia della libreria flip, dov'è il codice che non ti funziona?

**Comment by mattyX20** [comment]
Guardi nel index.js quando vado a sostituire a on.(click)......this....(.character-container).show diventa .flip poi nel container dichiarò id= card perché la libreria vuole così poi le immagini con class front e la descrizione con classe black salvo e sparisce tutto forse é qualcosa nel js

**Comment by jenkin** [comment]
Io qui continuo a leggere `.show()`, non c'è traccia di `.flip()`: https://github.com/mattyX20/Superheroes/blob/Develop/page/src/js/index.js#L17.

**Comment by mattyX20** [comment]
si scusi sta nella versione precedente scusi

**Comment by mattyX20** [comment]
Versione del 9 gennaio

**Comment by jenkin** [comment]
Ho aperto una pull request: https://github.com/mattyX20/Superheroes/pull/2

**Comment by mattyX20** [comment]
Vista domani lo scarico e lo sostituisco poi le farò sapere... grazie mille, buona serata.

**Comment by mattyX20** [comment]
Scaricato ho soltanto modificato il parametro .flip('toggle') sostituito con ('true') senno non mi funzionava.

**Comment by mattyX20** [comment]
Comunque sbagliavo io nel JS
